'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const fs=require('node:fs'),path=require('node:path');
const C=require('../netlify/functions/_lib/counseling');
const cases=require('../netlify/functions/_lib/handlers/counseling-cases').handler;
const session=require('../netlify/functions/_lib/handlers/counseling-session').handler;
const getUser=require('../netlify/functions/get-user').handler;
const saveUser=require('../netlify/functions/save-user').handler;
const saveLog=require('../netlify/functions/save-log').handler;
const createAi=require('../netlify/functions/_lib/handlers/counseling-ai').createHandler;
const administer=require('../netlify/functions/_lib/handlers/counseling-admin').handler;
const ids={auth:'10000000-0000-4000-8000-000000000001',teacher:'10000000-0000-4000-8000-000000000002',student:'10000000-0000-4000-8000-000000000003',other:'10000000-0000-4000-8000-000000000004',studentUser:'10000000-0000-4000-8000-000000000005'};
const profile={id:ids.teacher,google_id:ids.auth,name:'합성 교사',email:'demo@example.invalid',role:'교사',approved:true};
const student={student_id:ids.student,name:'합성 학생',student_number:'10101',academic_year:2026,school_stage:'high',grade:1};
// Existing pre-workflow fixtures intentionally retain legacy behavior.
function legacySample(){const c=C.newCase(student,{id:ids.teacher,display_name:'합성 교사'});const s=c.sessions[0];delete s.workflow_version;s.topic='실험 계획';s.teacher_opinion='측정 횟수를 정하고 오차 조건을 기록한다.';s.actions=[{id:C.newId(),text:'측정 기록표 작성',due_date:'2026-09-18',status:'planned'}];return c;}
function event(method='GET',b,q={}){return {httpMethod:method,headers:{authorization:'Bearer synthetic-token'},queryStringParameters:q,body:b===undefined?null:JSON.stringify(b)};}
const parse=r=>JSON.parse(r.body);
function mock({person=profile,grants=['teacher'],assigned=true,stored=legacySample(),rpcConflict=false}={}){
 const calls=[];let current=stored;
 global.fetch=async(url,opts={})=>{
  calls.push({url,opts});const p=String(url);let data;
  if(p.endsWith('/auth/v1/user'))data={id:ids.auth,email:'demo@example.invalid'};
  else if(p.includes('/users?')||p.endsWith('/users'))data=opts.method==='POST'||opts.method==='PATCH'?[{...person,...JSON.parse(opts.body)}]:person?[person]:[];
  else if(p.includes('counseling_roles?'))data=grants.map(role=>({role}));
  else if(p.includes('counseling_assignments?'))data=assigned?[{student_id:ids.student}]:[];
  else if(p.includes('counseling_students?'))data=[{id:ids.student,user_id:ids.studentUser,name:student.name}];
  else if(p.includes('counseling_student_numbers?'))data=[student];
  else if(p.includes('counseling_cases?'))data=current?[{data:current,student_id:current.student.student_id}]:[];
  else if(p.includes('rpc/counseling_write_case')){if(rpcConflict)return new Response(JSON.stringify({code:'40001'}),{status:409});current=JSON.parse(opts.body).p_case;data=current;}
  else if(p.endsWith('/logs'))data=[];
  else throw new Error('Unexpected external request '+p);
  return new Response(JSON.stringify(data),{status:200,headers:{'Content-Type':'application/json'}});
 };
 return {calls,current:()=>current};
}
test.beforeEach(()=>{process.env.COUNSELING_STORAGE='supabase';process.env.SUPABASE_URL='https://synthetic.invalid';process.env.SUPABASE_SERVICE_KEY='synthetic-service-key';process.env.COUNSELING_SERVER_AI_ENABLED='false';delete process.env.LLM_MODEL;delete process.env.GEMINI_API_KEY;});
test.afterEach(()=>{delete global.fetch;});
test('session rejects missing token before any request',async()=>{const m=mock();const e=event();e.headers={};assert.equal((await session(e)).statusCode,401);assert.equal(m.calls.length,0);});
test('null school approval never grants counseling access',async()=>{mock({person:{...profile,approved:null}});assert.equal((await session(event())).statusCode,403);});
test('explicit school approval without counseling role is denied',async()=>{mock({grants:[]});assert.equal((await session(event())).statusCode,403);});
test('teacher role cannot call manager registration',async()=>{const m=mock();assert.equal((await administer(event('POST',{action:'role',user_id:ids.other,role:'manager',approved:true}))).statusCode,403);assert.ok(!m.calls.some(c=>c.url.includes('rpc/')));});
test('school role must match an explicit counseling grant',async()=>{mock({person:{...profile,role:'학생'},grants:['teacher']});assert.equal((await session(event())).statusCode,403);});
test('approved teacher sees only assigned student metadata',async()=>{mock();const r=await session(event());assert.equal(r.statusCode,200);assert.equal(parse(r).students[0].student_id,ids.student);assert.equal(parse(r).ai.server,false);assert.equal(parse(r).user.authId,undefined);});
test('unassigned teacher cannot read/export/report another case',async()=>{const c=legacySample();for(const action of ['', 'export','report']){mock({assigned:false,stored:c});assert.equal((await cases(event('GET',undefined,{id:c.id,action}))).statusCode,404);}});
test('student cannot read unpublished drafts or write and confirm',async()=>{const c=legacySample();mock({person:{...profile,id:ids.studentUser,role:'학생'},grants:['student'],stored:c});assert.equal((await cases(event('GET',undefined,{id:c.id}))).statusCode,404);assert.equal((await cases(event('POST',{revision:1},{id:c.id,action:'confirm'}))).statusCode,403);});
test('new case identity comes from registered assignment and server teacher',async()=>{const m=mock();const r=await cases(event('POST',{student:{student_id:ids.student},teacher:{display_name:'forged'}}));assert.equal(r.statusCode,201);assert.equal(parse(r).case.teacher.display_name,profile.name);assert.equal(parse(r).case.privacy,'standard');assert.equal(m.current().revision,1);});
test('case owner and review forgery are rejected',async()=>{for(const change of [c=>{c.student.student_id=ids.other},c=>{c.sessions[0].review={state:'passed'}}]){const c=legacySample(),incoming=structuredClone(c);change(incoming);mock({stored:c});assert.equal((await cases(event('PUT',{case:incoming},{id:c.id}))).statusCode,400);}});
test('revision races become 409 and do not claim successful save',async()=>{const c=legacySample();mock({stored:c,rpcConflict:true});assert.equal((await cases(event('POST',{revision:1},{id:c.id,action:'next'}))).statusCode,409);});
test('edit clears review; direct confirm needs same content hash',async()=>{const c=legacySample();c.sessions[0].review=C.reviewSession(c.sessions[0]);const changed=structuredClone(c);changed.sessions[0].topic='새 주제';mock({stored:c});const r=await cases(event('PUT',{case:changed},{id:c.id}));assert.equal(parse(r).case.sessions[0].review,null);const m=mock({stored:parse(r).case});assert.equal((await cases(event('POST',{revision:2,session_id:c.current_session_id,review_acknowledged:true},{id:c.id,action:'confirm'}))).statusCode,409);assert.equal(m.current().revision,2);});
test('manual review remains pending until teacher acknowledgment',async()=>{const c=legacySample(),m=mock({stored:c});const r=await cases(event('POST',{revision:1,session_id:c.current_session_id},{id:c.id,action:'review'}));assert.equal(parse(r).review.state,'pending');const confirmed=await cases(event('POST',{revision:2,session_id:c.current_session_id,review_acknowledged:true},{id:c.id,action:'confirm'}));assert.equal(confirmed.statusCode,200);assert.equal(parse(confirmed).case.sessions[0].confirmed.teacher_id,ids.teacher);assert.equal(m.current().revision,3);});
test('confirmed session cannot be edited; next preserves original',async()=>{const c=legacySample();c.sessions[0].confirmed={at:C.now(),content_hash:C.hashSession(c.sessions[0])};const incoming=structuredClone(c);incoming.sessions[0].topic='변경';mock({stored:c});assert.equal((await cases(event('PUT',{case:incoming},{id:c.id}))).statusCode,409);const r=await cases(event('POST',{revision:1},{id:c.id,action:'next'}));assert.deepEqual(parse(r).case.sessions[0],c.sessions[0]);assert.equal(parse(r).case.sessions.length,2);});
test('in_progress action is accepted and direct quotes do not force rewriting',async()=>{const c=legacySample();c.sessions[0].actions[0].status='in_progress';c.sessions[0].student_question='학생의 말: 다양한 실험을 해 보고 싶어요.';C.validateCase(c);const review=C.reviewSession(c.sessions[0]);assert.equal(review.state,'pending');assert.ok(review.notes.some(n=>n.includes('직접 인용')));c.sessions[0].review=review;mock({stored:c});assert.equal((await cases(event('POST',{revision:1,session_id:c.current_session_id,review_acknowledged:true},{id:c.id,action:'confirm'}))).statusCode,200);});
test('local-only/record/analysis bundle never reaches database write',async()=>{for(const mutate of [c=>{c.privacy='local_only'},c=>{c.sessions[0].record={text:'private'}},c=>{c.sessions[0].analysis={summary:'private'}}]){const c=legacySample();mutate(c);const m=mock();const r=await cases(event('POST',{bundle:{format:'daeryun-counseling',version:1,case:c},student_id:ids.student,student_confirmed:true},{action:'import'}));assert.equal(r.statusCode,400);assert.ok(!m.calls.some(c=>c.url.includes('rpc/')));}});
test('import requires matching student and creates unconfirmed copy',async()=>{const c=legacySample();c.sessions[0].review=C.reviewSession(c.sessions[0]);c.sessions[0].confirmed={at:C.now()};mock();const r=await cases(event('POST',{bundle:{format:'daeryun-counseling',version:1,case:c},student_id:ids.student,student_confirmed:true},{action:'import'}));assert.equal(r.statusCode,201);const copy=parse(r).case;assert.notEqual(copy.id,c.id);assert.equal(copy.sessions[0].confirmed,null);assert.ok(copy.sessions[0].imported_history.confirmed);});
test('print output escapes student and teacher input; draft label retained',()=>{const c=legacySample();c.sessions[0].topic='<script>alert(1)</script>';const html=C.report(c,c.sessions[0]);assert.ok(html.includes('&lt;script&gt;'));assert.ok(!html.includes('<script>alert'));assert.ok(html.includes('초안'));});
test('legacy get-user rejects spoofed UID',async()=>{mock();assert.equal((await getUser(event('POST',{google_id:ids.other}))).statusCode,403);});
test('legacy save-user rejects approval injection and role upgrade',async()=>{mock();assert.equal((await saveUser(event('POST',{name:'synthetic',role:'교사',approved:true}))).statusCode,400);mock({person:{...profile,role:'학생'}});assert.equal((await saveUser(event('POST',{name:'synthetic',role:'교사'}))).statusCode,403);});
test('legacy signup is bound to auth identity and never self-approves',async()=>{const m=mock({person:null});const r=await saveUser(event('POST',{name:'synthetic',role:'학생',grade:1,class:1,student_number:1}));assert.equal(r.statusCode,200);const sent=JSON.parse(m.calls.find(c=>c.opts.method==='POST').opts.body);assert.equal(sent.google_id,ids.auth);assert.equal(sent.approved,false);assert.equal(sent.admission_year,1);assert.equal(Object.hasOwn(sent,'student_number'),false);});
test('legacy log rejects forged user ID',async()=>{mock();assert.equal((await saveLog(event('POST',{user_id:ids.other,event_type:'접속'}))).statusCode,403);});
test('standard AI uses stored accessible case and existing module response shape',async()=>{const c=legacySample();mock({stored:c});process.env.COUNSELING_SERVER_AI_ENABLED='true';process.env.LLM_MODEL='synthetic-model';process.env.GEMINI_API_KEY='synthetic-key';let sent;const ai=createAi(async args=>{sent=args;return {ok:true,status:200,data:{candidates:[{content:{parts:[{text:'확인 질문 초안'}]}}]}}});const r=await ai(event('POST',{case_id:c.id,session_id:c.current_session_id,revision:1,privacy:'standard',purpose:'counseling'}));assert.equal(r.statusCode,200);assert.equal(parse(r).text,'확인 질문 초안');assert.ok(!JSON.stringify(sent.payload).includes(student.name));});
test('AI rejects raw prompt and local-only provenance before provider call',async()=>{const c=legacySample();mock({stored:c});let calls=0;const ai=createAi(async()=>{calls++;});for(const extra of [{prompt:'private'},{privacy:'local_only'}]){const r=await ai(event('POST',{case_id:c.id,session_id:c.current_session_id,revision:1,privacy:'standard',purpose:'style',...extra}));assert.equal(r.statusCode,400);}assert.equal(calls,0);});
test('migration enables every new table RLS and service-only mutation RPCs',()=>{const sql=fs.readFileSync(path.join(__dirname,'../supabase/migrations/202609110001_counseling.sql'),'utf8');const tables=[...sql.matchAll(/create table public\.(counseling_\w+)/g)].map(m=>m[1]);assert.equal(tables.length,7);for(const t of tables)assert.ok(sql.includes(`alter table public.${t} enable row level security`),t);assert.ok(sql.includes('for update;'));assert.ok(sql.includes("errcode='40001'"));assert.ok(sql.includes('from public,anon,authenticated'));assert.ok(sql.includes('revoke insert,update,delete on public.users from anon,authenticated'));assert.ok(!/create policy[^;]*for (insert|update|all)/i.test(sql));});
