import test from 'node:test'
import assert from 'node:assert/strict'
import {modeForHost,parseBackup,readSessionToken,pdfBase64,assertStandard,clone} from '../src/lib/model'
import {LocalTransport} from '../src/lib/localTransport'
import {CloudTransport} from '../src/lib/cloudTransport'
import {checked,ApiError} from '../src/lib/transport'
import type {CounselingCase,Backup} from '../src/lib/types'
const example=():CounselingCase=>({schema_version:1,id:'case-1',revision:3,privacy:'local_only',created_at:'2026-09-11',updated_at:'2026-09-11',origin:'synthetic',student:{student_id:'student-1',student_number:'10101',academic_year:2026,school_stage:'high',grade:1,name:'합성학생'},teacher:{display_name:'합성교사'},current_session_id:'session-a',sessions:[{id:'session-a',date:'2026-09-11',topic:'질문과 다음 행동',student_question:'궁금한 점',context:'',evidence_notes:'',teacher_opinion:'함께 확인할 점',actions:[],next_date:'',record:null,analysis:null,review:null,confirmed:null},{id:'session-b',date:'2026-09-18',topic:'다음 상담',student_question:'',context:'',evidence_notes:'',teacher_opinion:'',actions:[],next_date:'',record:null,analysis:null,review:null,confirmed:null}]})
const bundle=(value=example()):Backup=>({format:'daeryun-counseling',version:1,case:value})
test('only loopback hosts activate local processing',()=>{for(const host of ['localhost','127.0.0.1','[::1]'])assert.equal(modeForHost(host),'local');for(const host of ['daeryun.life','localhost.example.com','127.0.0.1.evil.test','192.168.1.2'])assert.equal(modeForHost(host),'online')})
test('existing daeryun session uses token, not role or alternate access_token',()=>{assert.equal(readSessionToken({getItem:()=>JSON.stringify({token:'expected',access_token:'wrong',user:{role:'teacher'}})}),'expected');assert.equal(readSessionToken({getItem:()=>JSON.stringify({access_token:'wrong'})}),null);assert.equal(readSessionToken({getItem:()=>'{'}),null)})
test('private backup is rejected before online import, even if privacy label changes',()=>{assert.throws(()=>parseBackup(JSON.stringify(bundle()),'online'),/온라인/);const value=example();value.privacy='standard';value.sessions[0]!.analysis={} as never;assert.throws(()=>parseBackup(JSON.stringify(bundle(value)),'online'),/온라인/);assert.throws(()=>assertStandard(value),/온라인/)})
test('backup validation rejects malformed JSON and missing sessions',()=>{assert.throws(()=>parseBackup('{','local'),/JSON/);const invalid=bundle();invalid.case.sessions=[];assert.throws(()=>parseBackup(JSON.stringify(invalid),'local'),/회차/);assert.equal(parseBackup(JSON.stringify(bundle()),'local').case.student.student_number,'10101')})
test('PDF validation checks bytes and size before sending',async()=>{await assert.rejects(pdfBase64(new File(['not a pdf'],'record.pdf')),/형식/);await assert.rejects(pdfBase64(new File(['%PDF-1.7'],'record.txt')),/PDF/);const encoded=await pdfBase64(new File(['%PDF-1.7\nsynthetic'],'record.pdf'));assert.equal(atob(encoded),'%PDF-1.7\nsynthetic')})
test('local mutation carries health CSRF token, current revision and selected session ID',async()=>{const original=globalThis.fetch;const requests:{url:string;options:RequestInit}[]=[];globalThis.fetch=(async(input,options={})=>{requests.push({url:String(input),options});if(String(input).endsWith('/health'))return new Response(JSON.stringify({mode:'local',demo:true,csrf_token:'csrf-test',teacher:null,ollama:{available:true,models:[]}}));return new Response(JSON.stringify({job:{id:'job-1',state:'queued'}}))}) as typeof fetch;try{const api=new LocalTransport();await api.health();await api.analyze(example(),'session-b','local-model','목표',90);assert.equal((requests[1]!.options.headers as Record<string,string>)['X-Counseling-Token'],'csrf-test');assert.deepEqual(JSON.parse(String(requests[1]!.options.body)),{revision:3,session_id:'session-b',model:'local-model',goal:'목표',time_budget_minutes:90});assert.ok(requests.every(r=>r.url.startsWith('/api/')));assert.equal('generalAi' in api,false)}finally{globalThis.fetch=original}})
test('cloud private routes cannot dispatch network calls',async()=>{const original=globalThis.fetch;let calls=0;globalThis.fetch=(async()=>{calls++;throw new Error('unexpected')}) as typeof fetch;try{const api=new CloudTransport();await assert.rejects(api.upload(),/로컬/);await assert.rejects(api.analyze(),/로컬/);await assert.rejects(api.save(example()),/온라인/);await assert.rejects(api.importBackup(bundle()),/온라인/);assert.equal(calls,0)}finally{globalThis.fetch=original}})
test('409 surfaces actionable conflict without silently changing local draft',async()=>{const value=example(),before=clone(value);await assert.rejects(checked(new Response(JSON.stringify({error:{code:'revision_conflict',message:'internal detail'}}),{status:409})),(error:unknown)=>error instanceof ApiError&&error.status===409&&error.message.includes('백업'));assert.deepEqual(value,before)})
test('personal Gemini key is sent in a header and identifying fields are excluded from prompt',async()=>{const original=globalThis.fetch;let captured:{url:string;options:RequestInit}|undefined;globalThis.fetch=(async(input,options={})=>{captured={url:String(input),options};return new Response(JSON.stringify({candidates:[{content:{parts:[{text:'검토할 초안'}]}}]}))}) as typeof fetch;try{const value=example();value.privacy='standard';const result=await new CloudTransport().generalAi(value,'session-a',{provider:'gemini',model:'configured-model',apiKey:'private-test-key',ollamaUrl:''});assert.equal(result,'검토할 초안');assert.ok(!captured!.url.includes('private-test-key'));assert.equal((captured!.options.headers as Record<string,string>)['x-goog-api-key'],'private-test-key');assert.ok(!String(captured!.options.body).includes('10101'));assert.ok(!String(captured!.options.body).includes('합성학생'))}finally{globalThis.fetch=original}})
test('online Ollama provider rejects remote host and cloud model before fetch',async()=>{const value=example();value.privacy='standard';const api=new CloudTransport();await assert.rejects(api.generalAi(value,'session-a',{provider:'ollama',model:'local-model',apiKey:'',ollamaUrl:'https://example.com'}),/이 PC/);await assert.rejects(api.generalAi(value,'session-a',{provider:'ollama',model:'model:cloud',apiKey:'',ollamaUrl:'http://127.0.0.1:11434'}),/로컬 모델/)})
