import test from 'node:test'
import assert from 'node:assert/strict'
import {modeForHost,parseBackup,readSessionToken,pdfBase64,assertStandard,clone,emptyStrategy,reportFilename,normalizeCase,studentView,applyAnalysis} from '../src/lib/model'
import {LocalTransport} from '../src/lib/localTransport'
import {CloudTransport} from '../src/lib/cloudTransport'
import {checked,ApiError,isRevisionConflict} from '../src/lib/transport'
import type {CounselingCase,Backup} from '../src/lib/types'
const example=():CounselingCase=>({schema_version:1,id:'case-1',revision:3,privacy:'local_only',created_at:'2026-09-11',updated_at:'2026-09-11',origin:'synthetic',student:{student_id:'student-1',student_number:'10101',academic_year:2026,school_stage:'high',grade:1,name:'합성학생'},teacher:{display_name:'합성교사'},current_session_id:'session-a',sessions:[{id:'session-a',date:'2026-09-11',topic:'질문과 다음 행동',student_question:'궁금한 점',context:'',evidence_notes:'',teacher_opinion:'함께 확인할 점',actions:[],next_date:'',record:null,analysis:null,review:null,confirmed:null},{id:'session-b',date:'2026-09-18',topic:'다음 상담',student_question:'',context:'',evidence_notes:'',teacher_opinion:'',actions:[],next_date:'',record:null,analysis:null,review:null,confirmed:null}]})
const bundle=(value=example()):Backup=>({format:'daeryun-counseling',version:1,case:value})
test('only loopback hosts activate local processing',()=>{for(const host of ['localhost','127.0.0.1','[::1]'])assert.equal(modeForHost(host),'local');for(const host of ['daeryun.life','localhost.example.com','127.0.0.1.evil.test','192.168.1.2'])assert.equal(modeForHost(host),'online')})
test('existing daeryun session uses token, not role or alternate access_token',()=>{assert.equal(readSessionToken({getItem:()=>JSON.stringify({token:'expected',access_token:'wrong',user:{role:'teacher'}})}),'expected');assert.equal(readSessionToken({getItem:()=>JSON.stringify({access_token:'wrong'})}),null);assert.equal(readSessionToken({getItem:()=>'{'}),null)})
test('private backup is rejected before online import, even if privacy label changes',()=>{assert.throws(()=>parseBackup(JSON.stringify(bundle()),'online'),/온라인/);const value=example();value.privacy='standard';value.sessions[0]!.analysis={} as never;assert.throws(()=>parseBackup(JSON.stringify(bundle(value)),'online'),/온라인/);assert.throws(()=>assertStandard(value),/온라인/)})
test('backup validation rejects malformed JSON and missing sessions',()=>{assert.throws(()=>parseBackup('{','local'),/JSON/);const invalid=bundle();invalid.case.sessions=[];assert.throws(()=>parseBackup(JSON.stringify(invalid),'local'),/회차/);assert.equal(parseBackup(JSON.stringify(bundle()),'local').case.student.student_number,'10101')})
test('PDF validation checks bytes and size before sending',async()=>{await assert.rejects(pdfBase64(new File(['not a pdf'],'record.pdf')),/형식/);await assert.rejects(pdfBase64(new File(['%PDF-1.7'],'record.txt')),/PDF/);const encoded=await pdfBase64(new File(['%PDF-1.7\nsynthetic'],'record.pdf'));assert.equal(atob(encoded),'%PDF-1.7\nsynthetic')})
test('local mutation carries health CSRF token, current revision and selected session ID',async()=>{const original=globalThis.fetch;const requests:{url:string;options:RequestInit}[]=[];globalThis.fetch=(async(input,options={})=>{requests.push({url:String(input),options});if(String(input).endsWith('/health'))return new Response(JSON.stringify({mode:'local',demo:true,csrf_token:'csrf-test',teacher:null,ollama:{available:true,models:[]}}));return new Response(JSON.stringify({job:{id:'job-1',state:'queued'}}))}) as typeof fetch;try{const api=new LocalTransport();await api.health();await api.analyze(example(),'session-b','local-model','목표',90);assert.equal((requests[1]!.options.headers as Record<string,string>)['X-Counseling-Token'],'csrf-test');assert.deepEqual(JSON.parse(String(requests[1]!.options.body)),{revision:3,session_id:'session-b',model:'local-model',goal:'목표',time_budget_minutes:90});assert.ok(requests.every(r=>r.url.startsWith('/api/')));assert.equal('generalAi' in api,false)}finally{globalThis.fetch=original}})
test('cloud private routes cannot dispatch network calls',async()=>{const original=globalThis.fetch;let calls=0;globalThis.fetch=(async()=>{calls++;throw new Error('unexpected')}) as typeof fetch;try{const api=new CloudTransport();await assert.rejects(api.upload(),/로컬/);await assert.rejects(api.analyze(),/로컬/);await assert.rejects(api.save(example()),/온라인/);await assert.rejects(api.importBackup(bundle()),/온라인/);assert.equal(calls,0)}finally{globalThis.fetch=original}})
test('409 surfaces actionable conflict without silently changing local draft',async()=>{const value=example(),before=clone(value);await assert.rejects(checked(new Response(JSON.stringify({error:{code:'revision_conflict',message:'internal detail'}}),{status:409})),(error:unknown)=>error instanceof ApiError&&error.status===409&&error.message.includes('백업'));assert.deepEqual(value,before)})
test('personal Gemini key is sent in a header and identifying fields are excluded from prompt',async()=>{const original=globalThis.fetch;let captured:{url:string;options:RequestInit}|undefined;globalThis.fetch=(async(input,options={})=>{captured={url:String(input),options};return new Response(JSON.stringify({candidates:[{content:{parts:[{text:'검토할 초안'}]}}]}))}) as typeof fetch;try{const value=example();value.privacy='standard';const result=await new CloudTransport().generalAi(value,'session-a',{provider:'gemini',model:'configured-model',apiKey:'private-test-key',ollamaUrl:''});assert.equal(result,'검토할 초안');assert.ok(!captured!.url.includes('private-test-key'));assert.equal((captured!.options.headers as Record<string,string>)['x-goog-api-key'],'private-test-key');assert.ok(!String(captured!.options.body).includes('10101'));assert.ok(!String(captured!.options.body).includes('합성학생'))}finally{globalThis.fetch=original}})
test('online Ollama provider rejects remote host and cloud model before fetch',async()=>{const value=example();value.privacy='standard';const api=new CloudTransport();await assert.rejects(api.generalAi(value,'session-a',{provider:'ollama',model:'local-model',apiKey:'',ollamaUrl:'https://example.com'}),/이 PC/);await assert.rejects(api.generalAi(value,'session-a',{provider:'ollama',model:'model:cloud',apiKey:'',ollamaUrl:'http://127.0.0.1:11434'}),/로컬 모델/)})

test('legacy backup receives empty strategy without inventing publication and rejects invalid strategy data',()=>{const original=example(),normalized=parseBackup(JSON.stringify(bundle(original)),'local').case;assert.deepEqual(normalized.sessions[0]!.strategy,emptyStrategy());assert.equal(normalized.sessions[0]!.guidance,null);assert.equal(original.sessions[0]!.strategy,undefined);original.sessions[0]!.strategy={target_major:22} as never;assert.throws(()=>parseBackup(JSON.stringify(bundle(original)),'local'),/전략 항목/)})
test('student view excludes unpublished sessions and teacher notes even if a response includes them',()=>{const value=normalizeCase(example());assert.equal(studentView(value),null);value.sessions[0]!.guidance={published_at:'2026-09-12',published_by:'teacher'};value.sessions[0]!.strategy!.student_message='학생에게 전달할 계획';value.sessions[0]!.teacher_opinion='내부 판단';value.current_session_id='session-b';const view=studentView(value)!;assert.equal(view.current_session_id,'session-a');assert.equal(view.sessions.length,1);assert.equal(view.sessions[0]!.teacher_opinion,'');assert.equal(view.sessions[0]!.strategy!.student_message,'학생에게 전달할 계획');assert.equal(value.sessions[0]!.teacher_opinion,'내부 판단')})
test('analysis adoption fills only empty strategy fields and preserves existing teacher writing',()=>{const strategy={...emptyStrategy(),strengths:'교사가 확인한 강점'};const analysis={strengths:[{text:'모델 강점',guidance:'제안'}],improvements:[{text:'확인한 어려움',guidance:'구체적인 도움'}]} as never;assert.deepEqual(applyAnalysis(strategy,analysis),{...strategy,gaps:'확인한 어려움\n구체적인 도움'});assert.equal(strategy.gaps,'')})
test('publish is a distinct confirmed revision request, and local material never reaches it',async()=>{const original=globalThis.fetch,storage=globalThis.localStorage;const calls:{url:string;body:unknown}[]=[];Object.defineProperty(globalThis,'localStorage',{configurable:true,value:{getItem:()=>JSON.stringify({token:'synthetic-token'})}});globalThis.fetch=(async(input,options)=>{calls.push({url:String(input),body:JSON.parse(String(options?.body))});return new Response(JSON.stringify({case:example()}))}) as typeof fetch;try{const value=normalizeCase(example()),api=new CloudTransport();await assert.rejects(api.publish(value,'session-a'),/온라인/);value.privacy='standard';await assert.rejects(api.publish(value,'session-a'),/확정/);assert.equal(calls.length,0);value.sessions[0]!.confirmed={by:'teacher'};await api.publish(value,'session-a');assert.ok(calls[0]!.url.includes('action=publish'));assert.deepEqual(calls[0]!.body,{revision:3,session_id:'session-a'});value.sessions[0]!.guidance={published_at:'2026-09-12',published_by:'teacher'};await assert.rejects(api.publish(value,'session-a'),/이미/);assert.equal(calls.length,1)}finally{globalThis.fetch=original;Object.defineProperty(globalThis,'localStorage',{configurable:true,value:storage})}})

 test('only revision conflicts get backup instructions; student PDF prerequisite errors keep their explanation',async()=>{for(const code of ['revision_conflict','REVISION_CONFLICT'])await assert.rejects(checked(new Response(JSON.stringify({error:{code,message:'conflict'}}),{status:409})),(e:unknown)=>e instanceof ApiError&&isRevisionConflict(e)&&e.message.includes('백업'));for(const code of ['student_guidance_required','student_report_unconfirmed','GUIDANCE_REQUIRED'])await assert.rejects(checked(new Response(JSON.stringify({error:{code,message:'새 전략에 안내를 작성하고 검토·확정해 주세요.'}}),{status:409})),(e:unknown)=>e instanceof ApiError&&!isRevisionConflict(e)&&e.message==='새 전략에 안내를 작성하고 검토·확정해 주세요.')})
 test('download filenames distinguish student guidance from private teacher review',()=>{assert.equal(reportFilename('10101','2026-09-12','student'),'학종전략_10101_2026-09-12_학생안내.pdf');assert.equal(reportFilename('10101','2026-09-12','teacher'),'학종전략_10101_2026-09-12_교사검토.pdf')})
