import {test,expect,type Page,type Locator} from '@playwright/test'
import {readFile,mkdir} from 'node:fs/promises'
import {fileURLToPath} from 'node:url'
import {intuitiveApi,syntheticCase,onlineOrigin} from './fixtures/intuitive'
import type {AdmissionRoute} from '../src/lib/admissions'
import {newAdmissionTarget} from '../src/lib/profile'

async function backupCase(page:Page){const pending=page.waitForEvent('download');await page.getByRole('button',{name:'전략 백업 저장',exact:true}).click();const download=await pending;return JSON.parse(await readFile((await download.path())!,'utf8')).case}
async function auditScreenshot(page:Page,name:string){const folder=new URL('../../../_workspace/final-fix-20260914/screenshots/',import.meta.url);await mkdir(fileURLToPath(folder),{recursive:true});await page.screenshot({path:fileURLToPath(new URL(name+'.png',folder)),fullPage:true})}
async function examplesDoNotChangeDraft(page:Page,container:Locator,screenshot?:string){
 const before=await backupCase(page)
 const examples=container.locator('.field-example')
 expect(await examples.count()).toBeGreaterThan(0)
 for(const example of await examples.all()){
  const summary=example.locator('summary');await summary.focus();await page.keyboard.press('Enter')
  await expect(example).toHaveAttribute('open','')
  await expect(example.locator('p')).toBeVisible()
  if(screenshot){await auditScreenshot(page,screenshot);screenshot=undefined}
  await page.keyboard.press('Enter');await expect(example).not.toHaveAttribute('open')
 }
 expect(await backupCase(page)).toEqual(before)
}

test('signed-out online landing has one clear login action and no red error',async({page})=>{
 const api=await intuitiveApi(page,{mode:'online',authenticated:false,value:null})
 await page.goto(onlineOrigin+'/counseling/')
 const card=page.locator('.auth-card')
 await expect(card.getByRole('heading',{name:'학종 전략실 로그인',exact:true})).toBeVisible()
 await expect(card.locator('.primary:visible')).toHaveCount(1)
 const login=card.getByRole('link',{name:'로그인하고 전략실로 이동',exact:true})
 await expect(login).toHaveAttribute('href','/?login_return=%2Fcounseling%2F#login')
 await expect(login).not.toHaveAttribute('target')
 await auditScreenshot(page,'login-desktop')
 await page.setViewportSize({width:390,height:844})
 await auditScreenshot(page,'login-mobile-390')
 await login.focus();await expect(login).toBeFocused()
 await expect(page.getByRole('alert')).toHaveCount(0)
 expect(api.calls).toHaveLength(0)
 expect(api.outside).toEqual([]);expect(api.pageErrors).toEqual([])
})

test('expired login returns to a clean login screen while a server outage stays a visible error',async({page})=>{
 const api=await intuitiveApi(page,{mode:'online',status:401,value:null})
 await page.goto(onlineOrigin+'/counseling/')
 await expect(page.getByRole('link',{name:'로그인하고 전략실로 이동',exact:true})).toBeVisible()
 await expect(page.getByRole('alert')).toHaveCount(0)
 expect(api.calls.some(call=>call.path.endsWith('/counseling-session'))).toBe(true)
 expect(api.calls.some(call=>call.path.includes('counseling-cases'))).toBe(false)
 expect(api.pageErrors).toEqual([])
})

test('503 is not disguised as a normal signed-out state and offers a retry',async({page})=>{
 const api=await intuitiveApi(page,{mode:'online',status:503,value:null})
 await page.goto(onlineOrigin+'/counseling/')
 await expect(page.getByRole('heading',{name:'전략실에 연결하지 못했습니다',exact:true})).toBeVisible()
 await expect(page.getByRole('link',{name:'로그인하고 전략실로 이동',exact:true})).toHaveCount(0)
 await expect(page.getByRole('button',{name:'이용 상태 다시 확인',exact:true})).toBeEnabled()
 await page.getByRole('button',{name:'이용 상태 다시 확인',exact:true}).click()
 await expect.poll(()=>api.calls.filter(call=>call.path.endsWith('/counseling-session')).length).toBe(2)
 await expect(page.getByRole('heading',{name:'전략실에 연결하지 못했습니다',exact:true})).toBeVisible()
 expect(api.calls.some(call=>call.path.includes('counseling-cases'))).toBe(false)
 expect(api.pageErrors).toEqual([])
})

test('local signed-out page uses the teacher connection action without a red alert',async({page})=>{
 const api=await intuitiveApi(page,{authenticated:false,value:null})
 await page.goto('/counseling/')
 await expect(page.locator('.auth-card .primary:visible')).toHaveCount(1)
 await expect(page.getByRole('button',{name:'대륜고 계정으로 연결',exact:true})).toBeEnabled()
 await expect(page.locator('.advanced-auth')).not.toHaveAttribute('open')
 await expect(page.getByRole('alert')).toHaveCount(0)
 expect(api.calls.map(call=>call.path)).toEqual(['/api/health'])
})

test('profile, strategy and optional consultation examples remain display-only when opened with the keyboard',async({page})=>{
 const api=await intuitiveApi(page)
 await page.goto('/counseling/')
 await expect(page.getByLabel('관심 주제',{exact:true})).toHaveValue('')
 await examplesDoNotChangeDraft(page,page.locator('.profile-form'),'profile-example-desktop')
 await expect(page.getByLabel('관심 주제',{exact:true})).toHaveValue('')
 expect(api.calls.filter(call=>call.method==='PUT')).toHaveLength(0)
 await page.getByRole('button',{name:'상담·전략 수립',exact:true}).click()
 await examplesDoNotChangeDraft(page,page.locator('.strategy-editor'),'strategy-example-desktop')
 await expect(page.getByLabel('강점',{exact:true})).toHaveValue('')
 await expect(page.getByLabel('학생 안내 메시지',{exact:true})).toHaveValue('')
 await expect(page.getByRole('button',{name:'실행과제 추가',exact:true})).toHaveCount(0)
 await page.locator('.consultation-input > summary').click()
 await examplesDoNotChangeDraft(page,page.locator('.consultation-form'))
 await expect(page.getByLabel('학생 반응',{exact:true})).toHaveValue('')
 await expect(page.getByLabel('합의한 방향',{exact:true})).toHaveValue('')
 await expect(page.getByRole('button',{name:'상담 반영 완료',exact:true})).toBeDisabled()
 expect(api.session!.preparation).toBeNull()
 expect(api.outside).toEqual([]);expect(api.pageErrors).toEqual([])
})

for(const width of [390,320])test(`simple forms, details and student list remain usable at ${width}px`,async({page},testInfo)=>{
 const api=await intuitiveApi(page)
 await page.setViewportSize({width,height:844})
 await page.goto('/counseling/')
 await expect(page.getByLabel('관심 주제',{exact:true})).toBeVisible()
 expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(width)
 const example=page.locator('.profile-form .field-example').first()
 await example.locator('summary').focus();await page.keyboard.press('Enter')
 await expect(example.locator('p')).toBeVisible()
 expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(width)
 await auditScreenshot(page,`profile-example-${width}`)
 await page.getByRole('button',{name:'학생별 전략 목록',exact:true}).click()
 await expect(page.locator('.sidebar')).toHaveClass(/open/)
 const close=page.getByRole('button',{name:'학생 목록 닫기',exact:true})
 await close.focus();await page.keyboard.press('Enter')
 await expect(page.locator('.sidebar')).not.toHaveClass(/open/)
 await page.getByRole('button',{name:'상담·전략 수립',exact:true}).click()
 await page.getByLabel('교과 계획',{exact:true}).fill('합성 장문 '.repeat(180))
 await page.getByLabel('교과 계획',{exact:true}).focus();await page.keyboard.press('Tab')
 await expect(page.locator('#strategy-subject_plan').locator('..').locator('.field-example summary')).toBeFocused()
 await page.keyboard.press('Enter')
 expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(width)
 await page.screenshot({path:testInfo.outputPath(`strategy-${width}.png`),fullPage:true})
 await auditScreenshot(page,`strategy-${width}`)
 await page.getByRole('button',{name:'저장',exact:true}).click()
 await expect(page.locator('.save-state')).toHaveText('저장된 기록')
 await page.getByRole('button',{name:'학생별 전략 목록',exact:true}).click()
 const open=page.getByRole('button',{name:'새 전략',exact:true});await open.click()
 const modal=page.getByRole('dialog')
 await expect(modal).toBeVisible()
 const focusables=modal.locator('button:not(:disabled),input:not(:disabled),select:not(:disabled),textarea:not(:disabled)')
 await focusables.last().focus();await page.keyboard.press('Tab');await expect(focusables.first()).toBeFocused()
 await page.keyboard.press('Shift+Tab');await expect(focusables.last()).toBeFocused()
 await page.keyboard.press('Escape');await expect(modal).toHaveCount(0);await expect(open).toBeFocused()
 expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(width)
 expect(api.pageErrors).toEqual([])
})

for(const mode of ['local','online'] as const)test(`${mode} optional university choices survive save and reload at desktop and 320px`,async({page},testInfo)=>{
 const value=syntheticCase();value.privacy=mode==='online'?'standard':'local_only';value.sessions[0]!.profile!.target_major='기존 관심 전공은 보존'
 const api=await intuitiveApi(page,{mode,value})
 await page.goto(mode==='online'?onlineOrigin+'/counseling/':'/counseling/')
 await page.getByRole('button',{name:'기본자료 입력·수정',exact:true}).click()
 const editor=page.getByRole('region',{name:'희망 대학·전공·전형 입력',exact:true})
 await expect(editor.getByRole('region')).toHaveCount(0)
 await page.getByRole('button',{name:'희망 대학·전공 추가',exact:true}).click()
 await expect(page.getByLabel('희망 1 대학',{exact:true})).toBeFocused()
 await expect(page.getByLabel('희망 1 대입 학년도',{exact:true})).toHaveValue('')
 await page.getByLabel('희망 1 대학',{exact:true}).fill('합성 대학 A')
 await page.getByLabel('희망 1 모집단위·전공',{exact:true}).fill('생명과학과')
 await page.getByLabel('희망 1 전형 유형',{exact:true}).fill('학생부종합')
 await page.getByLabel('희망 1 전형명',{exact:true}).fill('합성 탐구 전형')
 await page.getByLabel('희망 1 대입 학년도',{exact:true}).fill('2029')
 await page.getByRole('button',{name:'희망 대학·전공 추가',exact:true}).click()
 await expect(page.getByLabel('희망 2 대학',{exact:true})).toBeFocused()
 await page.getByLabel('희망 2 모집단위·전공',{exact:true}).fill('탐색 중인 다른 전공')
 for(const width of [1280,320]){
  await page.setViewportSize({width,height:900})
  await editor.scrollIntoViewIfNeeded()
  expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(width)
  await page.screenshot({path:testInfo.outputPath(`admission-input-${mode}-${width}.png`)})
 }
 await page.getByRole('button',{name:'저장',exact:true}).click()
 await expect(page.locator('.save-state')).toHaveText('저장된 기록')
 const saved=structuredClone(api.session!.profile!.admission_targets)
 expect(saved).toHaveLength(2)
 expect(saved[0]).toMatchObject({university:'합성 대학 A',major:'생명과학과',admission_type:'학생부종합',admission_name:'합성 탐구 전형',admission_year:2029})
 expect(saved[1]).toMatchObject({university:'',major:'탐색 중인 다른 전공',admission_type:'',admission_name:'',admission_year:null})
 expect(api.session!.profile!.target_major).toBe('기존 관심 전공은 보존')
 await page.reload()
 await expect(page.locator('.profile-summary-grid')).toContainText('합성 대학 A · 생명과학과 · 학생부종합 · 합성 탐구 전형 · 2029학년도 대입')
 await page.getByRole('button',{name:'기본자료 입력·수정',exact:true}).click()
 await expect(page.getByLabel('희망 2 대학',{exact:true})).toHaveValue('')
 await expect(page.getByLabel('희망 2 대입 학년도',{exact:true})).toHaveValue('')
 await page.getByLabel('희망 2 대입 학년도',{exact:true}).fill('2029.5')
 const writes=api.calls.filter(call=>call.method==='PUT').length
 await page.getByRole('button',{name:'저장',exact:true}).click()
 await expect(page.getByRole('alert').filter({hasText:'대입 학년도'}).first()).toBeVisible()
 expect(api.calls.filter(call=>call.method==='PUT')).toHaveLength(writes)
 await page.getByLabel('희망 2 대입 학년도',{exact:true}).fill('')
 await page.getByRole('button',{name:'희망 1 삭제',exact:true}).click()
 await expect(page.getByLabel('희망 1 대학',{exact:true})).toBeFocused()
 await expect(page.getByLabel('희망 1 모집단위·전공',{exact:true})).toHaveValue('탐색 중인 다른 전공')
 await page.getByRole('button',{name:'저장',exact:true}).click()
 await expect(page.locator('.save-state')).toHaveText('저장된 기록')
 expect(api.session!.profile!.admission_targets).toEqual([saved[1]])
 expect(api.session!.profile!.target_major).toBe('기존 관심 전공은 보존')
 expect(api.outside).toEqual([]);expect(api.pageErrors).toEqual([])
})

test('university guidance keeps route conditions and year mismatch visible on desktop and 320px',async({page},testInfo)=>{
 const value=syntheticCase(),target={...newAdmissionTarget(),university:'한양대학교',major:'생명과학과',admission_type:'학생부종합',admission_name:'면접형',admission_year:2029}
 value.sessions[0]!.profile!.admission_targets=[target]
 const catalogue=JSON.parse(await readFile(new URL('../src/data/admissions.json',import.meta.url),'utf8'))
 const university=catalogue.universities.find((item:{name:string})=>item.name==='한양대학교') as {source_title:string;source_url:string;routes:AdmissionRoute[]}
 const expected={elements:university.routes.filter(route=>route.type==='학생부종합'&&route.name==='면접형'),source_title:university.source_title,source_url:university.source_url},api=await intuitiveApi(page,{value})
 expect(expected.elements).toHaveLength(1)
 await page.goto('/counseling/')
 const guide=page.getByRole('region',{name:'희망 대학별 입학·전공 안내',exact:true}),info=guide.locator('details').first()
 await expect(info).not.toHaveAttribute('open')
 await expect(info.locator('summary')).toContainText('한양대학교')
 await expect(info.locator('summary')).toContainText('2028학년도 참고자료 · 희망 2029학년도와 다름')
 await info.locator('summary').click()
 for(const route of expected.elements){
  await expect(info.getByRole('heading',{name:route.name,exact:true})).toBeVisible()
  for(const line of [...route.selection,...route.csat,...route.assessment,...route.interview,...route.courses,...route.exceptions,route.eligibility].filter(line=>Boolean(line)&&line!=='확인 범위: 없음'))await expect(info).toContainText(line)
 }
 await expect(info).toContainText('희망 대입 학년도의 확정 조건으로 적용하지 않습니다.')
 await expect(info).not.toContainText('확인 범위: 없음')
 await expect(info).toContainText('수능최저학력기준 없음')
 for(const link of await info.locator('a').all()){await expect(link).toHaveAttribute('target','_blank');await expect(link).toHaveAttribute('rel','noopener noreferrer')}
 await expect(info.getByRole('link',{name:expected.source_title,exact:true})).toHaveAttribute('href',expected.source_url)
 for(const width of [1280,320]){
  await page.setViewportSize({width,height:900})
  await info.evaluate(element=>element.scrollIntoView({block:'start'}))
  expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(width)
  await page.screenshot({path:testInfo.outputPath(`hanyang-interview-2029-${width}.png`)})
 }
 await page.getByRole('button',{name:'기본자료 입력·수정',exact:true}).click()
 await page.getByLabel('희망 1 전형명',{exact:true}).fill('')
 const editingInfo=page.getByRole('region',{name:'희망 대학별 입학·전공 안내',exact:true}).locator('details').first()
 await editingInfo.locator('summary').click()
 await expect(editingInfo.locator('.route-options')).toContainText('면접형')
 await expect(editingInfo.locator('.route-detail')).toHaveCount(0)
 await page.getByLabel('희망 1 전형명',{exact:true}).fill('확인되지 않은 합성 전형')
 await expect(editingInfo).toContainText('입력한 전형명과 일치하는 검토 자료가 없습니다.')
 await expect(editingInfo.locator('.route-detail')).toHaveCount(0)
 await page.getByLabel('희망 1 대학',{exact:true}).fill('')
 await expect(page.getByRole('region',{name:'희망 대학별 입학·전공 안내',exact:true})).toHaveCount(0)
 expect(api.calls.every(call=>call.method==='GET')).toBe(true)
 expect(api.outside).toEqual([]);expect(api.pageErrors).toEqual([])
})

test('school task conditions and activity outputs reach the confirmed final strategy without exposing teacher notes',async({page})=>{
 const value=syntheticCase(),session=value.sessions[0]!
 session.profile!.selected_subjects=['화법과 언어'];session.profile!.weekly_minutes=0
 session.strategy!.subject_plan='합성 기존 교과 계획';session.strategy!.inquiry_plan='합성 기존 탐구 계획'
 const api=await intuitiveApi(page,{value})
 await page.goto('/counseling/')
 await page.getByRole('combobox',{name:'자료 학기',exact:true}).selectOption('2')
 const task=page.locator('.school-task').filter({has:page.getByRole('heading',{name:'찬반 논제에 대한 입론문 작성 및 언어 요소 탐구하기',exact:true})}).first()
 await expect(task).toContainText('AI 활용 금지')
 await expect(task.locator('.help')).toContainText('금지')
 await expect(task.locator('.help')).not.toContainText('prohibited')
 await task.getByRole('button',{name:'계획에 담기',exact:true}).click()
 await expect(page.getByLabel('교과 계획',{exact:true})).toHaveValue(/합성 기존 교과 계획[\s\S]*AI 활용 금지/)
 await expect(page.getByLabel('탐구 계획',{exact:true})).toHaveValue('합성 기존 탐구 계획')
 await page.getByRole('button',{name:'자료·분석',exact:true}).click()
 await page.getByLabel('자료 검색',{exact:true}).fill('개인 성장 목표')
 await page.locator('.school-activities > summary').click()
 const activity=page.locator('.school-activities article').filter({has:page.getByRole('heading',{name:'개인 성장 목표의 실천 일지와 경험 공유',exact:true})})
 await expect(activity).toContainText('확인 필요')
 await activity.locator('summary').click();await expect(activity).toContainText('성장 활동 일지')
 await auditScreenshot(page,'activity-selection-desktop')
 await activity.getByRole('button',{name:'활동 초안에 담기',exact:true}).click()
 await expect(page.getByLabel('창체·봉사·독서·행동특성 전략',{exact:true})).toHaveValue(/성장 활동 일지/)
 await expect(page.getByLabel('창체·봉사·독서·행동특성 전략',{exact:true})).toHaveValue(/적용 범위 미확정/)
 await expect(page.locator('.action-card')).toHaveCount(0)
 await auditScreenshot(page,'activity-adopted-desktop')
 await page.setViewportSize({width:390,height:844})
 await auditScreenshot(page,'activity-adopted-mobile-390')
 await page.setViewportSize({width:1280,height:720})
 expect(api.calls.filter(call=>call.method==='PUT')).toHaveLength(0)
 await page.getByLabel('학생 안내 메시지',{exact:true}).fill('원문 AI 금지 조건을 지키며 수업 자료와 활동 일지의 활용 범위를 먼저 확인해 봅시다.')
 await page.locator('.consultation-input > summary').click()
 await page.getByLabel('상담일',{exact:false}).fill('2026-09-14')
 await page.getByLabel('학생 반응',{exact:true}).fill('합성: 추가 시간 없이 수업 안에서 할 범위를 확인함')
 await page.getByLabel('합의한 방향',{exact:true}).fill('합성: AI 금지 조건을 지키고 자료 활용 범위를 담당 교사에게 확인하기로 함')
 await page.getByRole('button',{name:'상담 반영 완료',exact:true}).click()
 await page.getByRole('button',{name:'분석·전략 보고서',exact:true}).click()
 await page.getByRole('button',{name:'자동 점검 후 직접 검토',exact:true}).click()
 await page.getByLabel('학생 근거·상담 반영·학습 및 탐구 전략을 확인했습니다.').check()
 await page.getByRole('button',{name:'합성 시연 회차 확정',exact:true}).click()
 await expect(page.locator('.student-result')).toContainText('AI 활용 금지')
 await expect(page.locator('.student-result')).toContainText('성장 활동 일지')
 await expect(page.locator('.student-result')).not.toContainText('비공개 근거 합성표식')
 expect(api.session!.strategy!.subject_plan).toContain('AI 활용 금지')
 expect(api.session!.preparation).toBeNull()
 expect(api.session!.strategy!.activity_plan).toContain('출처:')
 expect(api.session!.strategy!.activity_plan).toContain('개정')
 expect(api.session!.evidence_notes).toContain('CCE-CLASS-20260911-R001')
 expect(api.session!.actions).toHaveLength(0)
 expect(api.session!.confirmed).toBeTruthy()
 expect(api.outside).toEqual([]);expect(api.pageErrors).toEqual([])
})

test('published student view hides empty strategy items, examples and private preparation material',async({page},testInfo)=>{
 const value=syntheticCase(),session=value.sessions[0]!
 value.privacy='standard';session.profile!.learning_concerns='비공개 학생 고민 합성표식'
 session.strategy!.subject_plan='확인한 자료 두 개를 비교하는 학생 공개 계획'
 session.strategy!.student_message='비교 기준을 말로 설명하고 피드백을 받아 봅시다.'
 session.guidance={published_at:'2026-09-14T00:00:00Z',published_by:'synthetic-teacher'}
 session.actions=[{id:'synthetic-action',text:'비교 기준을 설명하기',due_date:'',status:'planned'}]
 const api=await intuitiveApi(page,{mode:'online',role:'student',value})
 await page.setViewportSize({width:320,height:844})
 await page.goto(onlineOrigin+'/counseling/')
 await expect(page.getByRole('article',{name:'학습·진로 전략 보고서 미리보기',exact:true})).toBeVisible()
 await expect(page.locator('.student-result .result-sections > section')).toHaveCount(2)
 for(const name of ['목표 전공','진로 방향','강점','보완점','탐구 계획','창체·봉사·독서·행동특성 전략','학기별 계획'])await expect(page.getByRole('heading',{name,exact:true})).toHaveCount(0)
 await expect(page.locator('textarea,input[type=file],.field-example,.teacher-notes,.preparation-snapshot,.consultation-form')).toHaveCount(0)
 await expect(page.getByText(/비공개.*합성표식/)).toHaveCount(0)
 await expect(page.locator('.student-result')).not.toContainText('미입력')
 expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(320)
 await page.screenshot({path:testInfo.outputPath('student-320.png'),fullPage:true})
 await auditScreenshot(page,'student-final-320')
 await page.setViewportSize({width:1280,height:720})
 await auditScreenshot(page,'student-final-desktop')
 expect(api.calls.every(call=>call.method==='GET')).toBe(true)
 expect(api.outside).toEqual([]);expect(api.pageErrors).toEqual([])
})
