import {test,expect} from '@playwright/test'
import {readFile} from 'node:fs/promises'

test('real demo server: student profile, synthetic PDF, review, backup restore and next-session continuity',async({page,request})=>{
 test.setTimeout(60000)
 const health=await (await request.get('/api/health')).json()
 test.skip(!health.demo,'This test writes synthetic records and runs only against the explicit demo server.')
 const errors:string[]=[],outside:string[]=[]
 page.on('pageerror',err=>errors.push(err.message))
 page.on('request',req=>{if(!['127.0.0.1','localhost','[::1]'].includes(new URL(req.url()).hostname))outside.push(req.url())})
 await page.goto('/counseling/')
 await page.getByRole('button',{name:'새 전략',exact:true}).click()
 await page.getByLabel('학번',{exact:true}).fill('19991')
 await page.getByLabel('학생 이름').fill('합성연동검증')
 await page.getByLabel('학년도',{exact:true}).fill('2026')
 await page.getByLabel('상담 교사',{exact:true}).fill('합성검증교사')
 await page.getByRole('button',{name:'첫 전략 만들기'}).click()
 await expect(page.getByRole('heading',{name:'교사 전략의 근거와 선택지를 검토합니다.'})).toBeVisible()
 const expectedProfile={target_major:'환경 분야 탐색',interests:'합성 자료에서 관찰 사실과 해석 구분하기',learning_concerns:'서술형 설명에서 근거를 빠뜨리는 상황 확인',selected_subjects:['공통국어1','통합과학1'],grades:[{subject:'공통국어1',academic_year:2026,semester:1,grade_scale:'5',rank_grade:3,score:84,achievement:'B'}]}
 await page.getByRole('button',{name:'기본자료 입력·수정'}).click()
 await page.getByLabel('관심 전공·계열',{exact:true}).fill(expectedProfile.target_major)
 await page.getByLabel('관심 주제',{exact:true}).fill(expectedProfile.interests)
 await page.getByLabel('학습 고민',{exact:true}).fill(expectedProfile.learning_concerns)
 await page.getByLabel('실제 이수 과목',{exact:true}).fill(expectedProfile.selected_subjects.join(', '))
 await page.getByRole('button',{name:'성적 추가',exact:true}).click()
 await page.getByLabel('성적 1 과목',{exact:true}).fill('공통국어1')
 await page.getByLabel('성적 1 학년도',{exact:true}).fill('2026')
 await page.getByLabel('성적 1 학기',{exact:true}).selectOption('1')
 await page.getByLabel('성적 1 등급 체계',{exact:true}).selectOption('5')
 await page.getByLabel('성적 1 석차등급',{exact:true}).fill('3')
 await page.getByLabel('성적 1 원점수',{exact:true}).fill('84')
 await page.getByLabel('성적 1 성취도',{exact:true}).fill('B')
 await page.getByRole('button',{name:'저장',exact:true}).click()
 await expect(page.getByText('작성한 전략을 저장했습니다.')).toBeVisible()
 await expect(page.getByLabel('관심 전공·계열',{exact:true})).toHaveValue(expectedProfile.target_major)
 await expect(page.locator('.profile-table-wrap')).toContainText('5등급제')
 await page.getByRole('button',{name:'교사 전략 수립',exact:true}).click()
 await page.locator('.teacher-notes').evaluate(el=>el.setAttribute('open',''))
 await page.getByLabel('전략 제목',{exact:true}).fill('자료에서 관찰 사실과 해석을 구분하는 질문 정하기')
 await page.getByLabel('목표 전공',{exact:true}).fill('관심 계열 탐색 중')
 await page.getByLabel('교과 계획',{exact:true}).fill('현재 수업 자료에서 관찰 사실과 해석을 구분해 설명하는 연습')
 await page.getByLabel('학생 안내 메시지',{exact:true}).fill('관찰한 사실과 해석을 나누고 비교 기준을 하나 정해 봅시다.')
 await page.getByLabel('학생의 질문',{exact:true}).fill('비교 기준을 하나로 좁히려면 어떤 자료를 확인할까요?')
 await page.getByLabel('이전 상담과 현재 상황',{exact:true}).fill('합성 학생부를 읽고 탐구 질문을 정하는 시연입니다.')
 await page.getByLabel('확인한 근거',{exact:true}).fill('제공된 고1 부분 작성 합성 학생부의 읽을 수 있는 항목을 확인합니다.')
 await page.getByLabel('교사의 의견',{exact:true}).fill('관찰 사실을 먼저 적고, 설명에 사용할 비교 기준을 하나 정해 봅니다.')
 await page.getByRole('button',{name:'실행과제 추가',exact:true}).click()
 await page.getByLabel('실행과제 1',{exact:true}).fill('비교할 자료 두 개를 찾아 공통점과 차이점을 각각 한 문장으로 적기')
 await page.getByRole('button',{name:'저장',exact:true}).click()
 await expect(page.getByText('작성한 전략을 저장했습니다.')).toBeVisible()
 await page.getByRole('button',{name:'자료·분석',exact:true}).click()
 await page.getByRole('button',{name:'학생부 PDF 근거',exact:true}).click()
 const pdfResponse=await request.get('/api/fixtures/high-1-partial.pdf')
 expect(pdfResponse.ok()).toBeTruthy()
 await page.locator('input[type=file][accept=".pdf,application/pdf"]').setInputFiles({name:'합성고1-연동검증.pdf',mimeType:'application/pdf',buffer:await pdfResponse.body()})
 await page.getByRole('button',{name:'항목 추출하기'}).click()
 await expect(page.getByText('추출 항목과 판독 상태를 확인해 주세요.',{exact:true})).toBeVisible()
 await expect(page.locator('details.evidence').first()).toBeVisible()
 await page.locator('details.evidence').first().locator('summary').click()
 await page.getByRole('button',{name:'자료·분석',exact:true}).click()
 await page.getByRole('button',{name:'Ollama 근거 분석',exact:true}).click()
 for(const item of health.ollama.models) await expect(page.getByLabel('이 PC의 Ollama 모델').locator('option').filter({hasText:item.name})).toHaveCount(1)
 // Real model analysis runs separately by the backend owner; avoid concurrent GPU work.
 await page.getByRole('button',{name:'교사 전략 수립',exact:true}).click()
 await page.getByRole('button',{name:'전략 준비 완료·상담으로',exact:true}).click()
 await expect(page.locator('.preparation-snapshot')).toContainText('현재 수업 자료에서 관찰 사실과 해석을 구분')
 await page.getByLabel('상담일',{exact:true}).fill('2026-09-12')
 await page.getByLabel('학생 반응',{exact:true}).fill('합성 시연: 자료 두 개를 비교할 수 있다고 설명함')
 await page.getByLabel('합의한 방향',{exact:true}).fill('합성 시연: 수업 자료 두 개의 관찰 근거를 한 문장씩 정리하기로 함')
 await page.getByLabel('수정할 점',{exact:true}).fill('합성 시연: 비교 기준을 하나로 좁힘')
 await page.getByRole('button',{name:'상담 반영 완료',exact:true}).click()
 await page.getByLabel('교과 계획',{exact:true}).fill('상담을 반영해 수업 자료 두 개와 비교 기준 하나로 설명 연습하기')
 await page.getByRole('button',{name:'자동 점검 후 직접 검토'}).click()
 await expect(page.getByText('교사 직접 확인 필요')).toBeVisible({timeout:30000})
 await page.getByLabel('원문 근거와 전략 내용, 문체 검토 의견을 확인했습니다.').check()
 await page.getByRole('button',{name:'합성 시연 회차 확정'}).click()
 await expect(page.getByText('합성 시연으로 확정한 회차입니다.',{exact:false})).toBeVisible()
 await page.screenshot({path:'test-results/local-confirmed.png',fullPage:true})
 const pdfDownload=page.waitForEvent('download')
 await page.getByRole('button',{name:'학생 안내 PDF 저장',exact:true}).first().click()
 const report=await pdfDownload
 await report.saveAs('test-results/local-synthetic-report.pdf')
 expect((await readFile((await report.path())!)).subarray(0,5).toString()).toBe('%PDF-')
 const jsonDownload=page.waitForEvent('download')
 await page.getByRole('button',{name:'JSON 백업',exact:true}).click()
 const backup=await jsonDownload
 const buffer=await readFile((await backup.path())!)
 const bundle=JSON.parse(buffer.toString('utf8'))
 expect(bundle.case.origin).toBe('synthetic')
 expect(bundle.case.sessions[0].confirmed.synthetic).toBe(true)
 expect(bundle.case.sessions[0].record.sections.length).toBeGreaterThan(0)
 expect(bundle.case.sessions[0].workflow_version).toBe(2)
 expect(bundle.case.sessions[0].consultation.status).toBe('completed')
 expect(bundle.case.sessions[0].preparation.strategy.subject_plan).toBe('현재 수업 자료에서 관찰 사실과 해석을 구분해 설명하는 연습')
 expect(bundle.case.sessions[0].strategy.subject_plan).toContain('상담을 반영해')
 const savedProfile=bundle.case.sessions[0].profile
 expect(savedProfile).toMatchObject(expectedProfile)
 expect(savedProfile.grades).toHaveLength(1)
 expect(savedProfile.grades[0].id).toMatch(/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i)
 await page.locator('input[type=file][accept=".json,application/json"]').setInputFiles({name:'합성검증-백업.json',mimeType:'application/json',buffer})
 await expect(page.getByRole('button',{name:'새 사본으로 가져오기'})).toBeDisabled()
 await page.getByLabel('학년도, 학번과 상담 학생이 맞는지 확인했습니다.').check()
 await page.getByRole('button',{name:'새 사본으로 가져오기'}).click()
 await expect(page.getByRole('dialog')).toHaveCount(0)
 await page.getByRole('button',{name:'기본자료 입력·수정'}).click()
 await expect(page.getByLabel('관심 전공·계열',{exact:true})).toHaveValue(expectedProfile.target_major)
 await expect(page.getByLabel('학습 고민',{exact:true})).toHaveValue(expectedProfile.learning_concerns)
 await expect(page.getByLabel('성적 1 원점수',{exact:true})).toHaveValue('84')
 await page.getByRole('button',{name:'교사 전략 수립',exact:true}).click()
 await expect(page.getByLabel('교사의 의견',{exact:true})).toBeEnabled()
 await page.getByRole('button',{name:'회차 추가',exact:true}).click()
 await expect(page.getByText('2차 전략',{exact:true})).toBeVisible()
 await page.getByRole('button',{name:'기본자료 입력·수정'}).click()
 await expect(page.getByLabel('관심 주제',{exact:true})).toHaveValue(expectedProfile.interests)
 await expect(page.getByLabel('실제 이수 과목',{exact:true})).toHaveValue(expectedProfile.selected_subjects.join(', '))
 await expect(page.getByLabel('성적 1 석차등급',{exact:true})).toHaveValue('3')
 const nextDownload=page.waitForEvent('download')
 await page.getByRole('button',{name:'JSON 백업',exact:true}).click()
 const nextBundle=JSON.parse((await readFile((await (await nextDownload).path())!)).toString('utf8'))
 expect(nextBundle.case.sessions).toHaveLength(2)
 expect(nextBundle.case.sessions[0].profile).toEqual(savedProfile)
 expect(nextBundle.case.sessions[1].profile).toEqual(savedProfile)
 expect(nextBundle.case.sessions[1].workflow_version).toBe(2)
 expect(nextBundle.case.sessions[1].preparation).toBeNull()
 expect(nextBundle.case.sessions[1].consultation.status).toBe('not_started')
 expect(nextBundle.case.current_session_id).toBe(nextBundle.case.sessions[1].id)
 expect(errors).toEqual([])
 expect(outside).toEqual([])
})
