import {test,expect} from '@playwright/test'
import {readFile} from 'node:fs/promises'

test('real demo server: synthetic PDF, manual review, confirmation, export and import',async({page,request})=>{
 const health=await (await request.get('/api/health')).json()
 test.skip(!health.demo,'This test writes synthetic records and runs only against the explicit demo server.')
 const errors:string[]=[],outside:string[]=[]
 page.on('pageerror',err=>errors.push(err.message))
 page.on('request',req=>{if(!['127.0.0.1','localhost','[::1]'].includes(new URL(req.url()).hostname))outside.push(req.url())})
 await page.goto('/counseling/')
 await page.getByRole('button',{name:'새 상담',exact:true}).click()
 await page.getByLabel('학번',{exact:true}).fill('19991')
 await page.getByLabel('학생 이름').fill('합성연동검증')
 await page.getByLabel('상담 교사',{exact:true}).fill('합성검증교사')
 await page.getByRole('button',{name:'첫 상담 만들기'}).click()
 await page.getByLabel('상담 목표',{exact:true}).fill('자료에서 관찰 사실과 해석을 구분하는 질문 정하기')
 await page.getByLabel('학생의 질문',{exact:true}).fill('비교 기준을 하나로 좁히려면 어떤 자료를 확인할까요?')
 await page.getByLabel('이전 상담과 현재 상황',{exact:true}).fill('합성 학생부를 읽고 탐구 질문을 정하는 시연입니다.')
 await page.getByLabel('확인한 근거',{exact:true}).fill('제공된 고1 부분 작성 합성 학생부의 읽을 수 있는 항목을 확인합니다.')
 await page.getByLabel('교사의 의견',{exact:true}).fill('관찰 사실을 먼저 적고, 설명에 사용할 비교 기준을 하나 정해 봅니다.')
 await page.getByRole('button',{name:'행동 추가',exact:true}).click()
 await page.getByLabel('다음 행동 1',{exact:true}).fill('비교할 자료 두 개를 찾아 공통점과 차이점을 각각 한 문장으로 적기')
 await page.getByRole('button',{name:'저장',exact:true}).click()
 await expect(page.getByText('작성한 상담을 저장했습니다.')).toBeVisible()
 await page.getByRole('button',{name:'학생부 근거',exact:true}).click()
 const pdfResponse=await request.get('/api/fixtures/high-1-partial.pdf')
 expect(pdfResponse.ok()).toBeTruthy()
 await page.locator('input[type=file][accept=".pdf,application/pdf"]').setInputFiles({name:'합성고1-연동검증.pdf',mimeType:'application/pdf',buffer:await pdfResponse.body()})
 await page.getByRole('button',{name:'항목 추출하기'}).click()
 await expect(page.getByText('추출 항목과 판독 상태를 확인해 주세요.',{exact:true})).toBeVisible()
 await expect(page.locator('details.evidence').first()).toBeVisible()
 await page.locator('details.evidence').first().locator('summary').click()
 await page.getByRole('button',{name:'분석과 전략',exact:true}).click()
 for(const item of health.ollama.models) await expect(page.getByLabel('이 PC의 Ollama 모델').locator('option').filter({hasText:item.name})).toHaveCount(1)
 // Real model analysis runs separately by the backend owner; avoid concurrent GPU work.
 await page.getByRole('button',{name:'검토와 확정',exact:true}).click()
 await page.getByRole('button',{name:'자동 점검 후 직접 검토'}).click()
 await expect(page.getByText('교사 직접 확인 필요')).toBeVisible({timeout:30000})
 await page.getByLabel('원문 근거와 상담 내용, 문체 검토 의견을 확인했습니다.').check()
 await page.getByRole('button',{name:'합성 시연 회차 확정'}).click()
 await expect(page.getByText('합성 시연으로 확정한 회차입니다.',{exact:false})).toBeVisible()
 await page.screenshot({path:'test-results/local-confirmed.png',fullPage:true})
 const pdfDownload=page.waitForEvent('download')
 await page.getByRole('button',{name:'PDF 내보내기',exact:true}).click()
 const report=await pdfDownload
 await report.saveAs('test-results/local-synthetic-report.pdf')
 expect((await readFile((await report.path())!)).subarray(0,5).toString()).toBe('%PDF-')
 const jsonDownload=page.waitForEvent('download')
 await page.getByRole('button',{name:'JSON 백업',exact:true}).click()
 const backup=await jsonDownload
 const buffer=await readFile((await backup.path())!)
 const bundle=JSON.parse(buffer.toString('utf8'))
 expect(bundle.case.origin).toBe('synthetic')
 expect(bundle.case.sessions[0].confirmed.synthetic).toBe(true)
 expect(bundle.case.sessions[0].record.sections.length).toBeGreaterThan(0)
 await page.locator('input[type=file][accept=".json,application/json"]').setInputFiles({name:'합성검증-백업.json',mimeType:'application/json',buffer})
 await expect(page.getByRole('button',{name:'새 사본으로 가져오기'})).toBeDisabled()
 await page.getByLabel('학년도, 학번과 상담 학생이 맞는지 확인했습니다.').check()
 await page.getByRole('button',{name:'새 사본으로 가져오기'}).click()
 await expect(page.getByRole('dialog')).toHaveCount(0)
 await expect(page.getByLabel('교사의 의견',{exact:true})).toBeEnabled()
 await page.getByRole('button',{name:'회차 추가',exact:true}).click()
 await expect(page.getByText('2회 상담',{exact:true})).toBeVisible()
 expect(errors).toEqual([])
 expect(outside).toEqual([])
})
