import test from 'node:test'
import assert from 'node:assert/strict'
import {emptyProfile,normalizeProfile,profileIssues,hasGradeData,gradeTrends,profileQuestions,missingProfile,adoptProfile} from '../src/lib/profile'
import {emptyStrategy,normalizeCase,studentView} from '../src/lib/model'
import {schoolMatches,adoptSchoolTask,taskReference,type SchoolContext,type SchoolAssessment} from '../src/lib/schoolContext'
import type {GradeRecord,CounselingCase,Student} from '../src/lib/types'
const grade=(overrides:Partial<GradeRecord>={}):GradeRecord=>({id:crypto.randomUUID(),subject:'수학',academic_year:2026,semester:1,grade_scale:'5',rank_grade:3,score:80,achievement:'B',...overrides})
const student:Student={student_id:'synthetic',student_number:'10101',academic_year:2026,school_stage:'high',grade:1}
test('profile legacy absence and partial objects gain defaults; explicit invalid data is not silently erased',()=>{assert.deepEqual(normalizeProfile(undefined),emptyProfile());assert.deepEqual(normalizeProfile({}),emptyProfile());assert.throws(()=>normalizeProfile(null),/형식/);assert.throws(()=>normalizeProfile({extra:'not allowed'}),/허용/);assert.throws(()=>normalizeProfile({interests:'x\0y'}),/제어/);assert.throws(()=>normalizeProfile({selected_subjects:['수학',' 수학 ']}),/중복/);assert.throws(()=>normalizeProfile({grades:[{...grade(),extra:'wrong'}]}),/허용/);assert.throws(()=>normalizeProfile({grades:[grade({id:'12345678-1234-7234-8234-123456789012'})]}),/식별자/)})
test('profile grade and time boundaries preserve zero and reject scale misuse',()=>{assert.equal(normalizeProfile({weekly_minutes:0,grades:[grade({score:0,rank_grade:null})]}).weekly_minutes,0);for(const minutes of [-1,2401,1.5,'30'])assert.throws(()=>normalizeProfile({weekly_minutes:minutes}),/가용/);assert.equal(normalizeProfile({weekly_minutes:2400}).weekly_minutes,2400);for(const record of [grade({rank_grade:6}),grade({grade_scale:'unknown',rank_grade:1}),grade({score:101}),grade({score:-1}),grade({academic_year:2101}),grade({semester:3 as never})])assert.ok(profileIssues({...emptyProfile(),grades:[record]}).length);assert.equal(profileIssues({...emptyProfile(),grades:[grade({grade_scale:'9',rank_grade:9})]}).length,0)})
test('grade trends compare only exact subject and same scale, and duplicate terms do not become a trend',()=>{const profile={...emptyProfile(),grades:[grade(),grade({semester:2,rank_grade:2}),grade({grade_scale:'9',rank_grade:6}),grade({subject:'수학 탐구',semester:2,rank_grade:1})]};const trends=gradeTrends(profile);assert.equal(trends.length,3);assert.match(trends.find(t=>t.subject==='수학'&&t.scale==='5등급제')!.description,/3 → 2026년 2학기 2등급/);assert.match(trends.find(t=>t.scale==='9등급제')!.description,/기록이 추가/);profile.grades.push(grade());assert.match(gradeTrends(profile)[0]!.description,/중복/);assert.ok(trends.every(t=>!t.description.includes('합격')))})
test('questions quote the specific inputs, include observed grade values, and missing information is not a weakness',()=>{const profile={...emptyProfile(),learning_concerns:'서술형에서 근거를 빠뜨림',activities:'자료 비교 역할을 맡음',grades:[grade()],weekly_minutes:0};const questions=profileQuestions(profile);assert.equal(questions[0]!.source,'입력 · 학습 고민');assert.equal(questions[0]!.evidence,'서술형에서 근거를 빠뜨림');assert.match(questions.find(q=>q.id==='grade')!.evidence,/석차등급 3 \/ 원점수 80/);assert.match(questions.find(q=>q.id==='time')!.question,/추가 시간을 요구하지 않고/);assert.ok(missingProfile(emptyProfile()).length);assert.equal(profileQuestions(emptyProfile()).length,0)})
test('adopting source-based proposals keeps teacher content and does not fabricate strengths or gaps',()=>{const profile={...emptyProfile(),target_major:'탐색 중',interests:'학교 주변 물의 변화',selected_subjects:['통합과학1'],activities:'모둠에서 관찰 기록을 정리함',weekly_minutes:0};const original={...emptyStrategy(),subject_plan:'교사가 이미 정한 수업 계획'};const draft=adoptProfile(profile,original);assert.equal(draft.subject_plan,original.subject_plan);assert.equal(draft.target_major,'탐색 중');assert.match(draft.inquiry_plan,/학교 주변 물의 변화/);assert.match(draft.semester_plan,/0분/);assert.equal(draft.student_message,'');assert.equal(draft.strengths,'');assert.equal(draft.gaps,'');assert.equal(original.target_major,'')})
test('teacher-only profile is absent from the student view even if a server response contains it',()=>{const value={schema_version:1,id:'case',revision:1,privacy:'standard',student,teacher:{display_name:'교사'},sessions:[{id:'session',topic:'안내 제목',strategy:emptyStrategy(),profile:{...emptyProfile(),learning_concerns:'교사 준비 자료'},guidance:{published_at:'2026-09-12',published_by:'teacher'},actions:[]}],current_session_id:'session'} as unknown as CounselingCase;assert.equal(normalizeCase(value).sessions[0]!.profile!.learning_concerns,'교사 준비 자료');assert.equal('profile' in studentView(value)!.sessions[0]!,false)})
const task:SchoolAssessment={id:'task-1',subject:'공통국어1',school_stage:'high',grade:1,academic_year:2026,semester:1,title:'사회적 쟁점 탐구',learning_topics:['환경'],steps:['질문 정하기'],outputs:['보고서'],conditions:['수업 중 작성'],rubric_excerpts:['발표 시간 8~12분 구간의 채점 예시'],timing:'5월 중',ai_status:'원문 조건 확인',source_label:'학교 평가계획',source_ref:{source_id:'source-1',json_pointer:'/subjects/0/tasks/0'},revision:2,verified_current:false}
const data:SchoolContext={schema_version:'1.0',reviewed_on:'2026-09-11',sources:[],applicability_rules:{},assessments:[task,{...task,id:'old',academic_year:2025}],clubs:[],activities:[]}
test('school tasks prioritize selected actual subjects and exact year/grade; middle and old years remain reference',()=>{assert.equal(schoolMatches(data,student,[]).selected.length,0);const matches=schoolMatches(data,student,['공통국어 1']);assert.deepEqual(matches.selected.map(t=>t.id),['task-1']);assert.deepEqual(matches.reference.map(t=>t.id),['old']);assert.equal(schoolMatches(data,{...student,school_stage:'middle',grade:3},['공통국어1']).selected.length,0);assert.equal(schoolMatches(data,student,[],'환경').reference.length,2)})
test('school task adoption retains original timing/conditions/source and cannot overwrite a teacher plan',()=>{const reference=taskReference(task);assert.match(reference,/5월 중/);assert.match(reference,/수업 중 작성/);assert.match(reference,/채점표 발췌\(필수 조건과 구분\): 발표 시간 8~12분/);assert.match(reference,/\/subjects\/0\/tasks\/0/);assert.ok(!reference.includes('2026-05-'));const draft=adoptSchoolTask(task,emptyStrategy());assert.match(draft.subject_plan,/현행/);assert.match(draft.inquiry_plan,/필수 참여로 확정하지 않고/);assert.equal(adoptSchoolTask(task,{...emptyStrategy(),subject_plan:'기존 계획'}).subject_plan,'기존 계획')})

 test('an unfinished grade row survives a backup and stays missing evidence until actual data is entered',()=>{const partial=grade({subject:'',grade_scale:'unknown',rank_grade:null,score:null,achievement:''});const restored=normalizeProfile(JSON.parse(JSON.stringify({...emptyProfile(),grades:[partial]})));assert.equal(restored.grades.length,1);assert.equal(hasGradeData(restored.grades[0]!),false);assert.ok(missingProfile(restored).includes('과목별 성적과 등급 체계'));assert.equal(profileQuestions(restored).length,0);restored.grades[0]!.subject='수학';restored.grades[0]!.score=0;assert.equal(hasGradeData(restored.grades[0]!),true)})
