<script setup lang="ts">
import {computed,nextTick,onMounted,onBeforeUnmount,ref,watch} from 'vue'
import {ArrowLeft,Check,RefreshCw,ShieldCheck,Users,UserRoundPlus,X,AlertCircle,LoaderCircle} from 'lucide-vue-next'
import type {Transport} from '../lib/types'
import {readableError} from '../lib/model'
import {schoolCounselingRole,validateAdminAction,type AdminAction,type AdminData,type ManagedUser} from '../lib/admin'
const props=defineProps<{api:Transport;canReturn:boolean}>()
const emit=defineEmits<{close:[];busy:[value:boolean]}>()
const data=ref<AdminData|null>(null),busy=ref(false),error=ref(''),notice=ref(''),pending=ref<AdminAction|null>(null),dialog=ref<HTMLDialogElement|null>(null)
const roleUserId=ref(''),roleApproved=ref(false),studentUserId=ref(''),studentName=ref(''),studentNumber=ref(''),year=ref(new Date().getFullYear()),stage=ref<'middle'|'high'>('high'),grade=ref(1)
const assignedStudentId=ref(''),assignedTeacherId=ref(''),assignmentActive=ref(true),search=ref('')
let previousFocus:HTMLElement|null=null
const roleUser=computed(()=>data.value?.users.find(item=>item.id===roleUserId.value))
const role=computed(()=>schoolCounselingRole(roleUser.value))
const studentUsers=computed(()=>data.value?.users.filter(item=>item.role==='학생')||[])
const teachers=computed(()=>data.value?.users.filter(item=>item.role==='교사')||[])
const assignmentRows=computed(()=>data.value?.assignments.filter(item=>{const label=studentLabel(item.student_id)+' '+userName(item.teacher_user_id);return label.includes(search.value.trim())})||[])
const approvedTeachers=computed(()=>teachers.value.filter(item=>item.approved&&data.value?.roles.some(grant=>grant.user_id===item.id&&grant.role==='teacher'&&grant.approved)).length)
const activeStudents=computed(()=>data.value?.students.filter(item=>item.active).length||0)
const activeAssignments=computed(()=>data.value?.assignments.filter(item=>item.active).length||0)
function userName(id:string){return data.value?.users.find(item=>item.id===id)?.name||'이름 확인 필요'}
function userLabel(user:ManagedUser){return `${user.name||'이름 확인 필요'} · ${user.role} · ${user.id.slice(-6)}${user.approved?'':' · 학교 승인 대기'}`}
function numberOf(id:string){return data.value?.numbers.filter(item=>item.student_id===id).sort((a,b)=>b.academic_year-a.academic_year)[0]}
function studentLabel(id:string){const student=data.value?.students.find(item=>item.id===id),number=numberOf(id);return `${number?number.academic_year+' · '+number.student_number:'학번 확인 필요'} ${student?.name||''}`}
watch(roleUser,()=>{roleApproved.value=Boolean(data.value?.roles.find(item=>item.user_id===roleUserId.value&&item.role===role.value)?.approved)})
watch(studentUserId,()=>{const user=data.value?.users.find(item=>item.id===studentUserId.value),existing=data.value?.students.find(item=>item.user_id===studentUserId.value),number=existing?numberOf(existing.id):null;studentName.value=existing?.name||user?.name||'';studentNumber.value=number?.student_number||'';year.value=number?.academic_year||new Date().getFullYear();stage.value=number?.school_stage||'high';grade.value=number?.grade||1})
watch([assignedStudentId,assignedTeacherId],()=>{assignmentActive.value=data.value?.assignments.find(item=>item.student_id===assignedStudentId.value&&item.teacher_user_id===assignedTeacherId.value)?.active??true})
watch(pending,async value=>{await nextTick();if(value){previousFocus=document.activeElement as HTMLElement;dialog.value?.showModal()}else{dialog.value?.close();previousFocus?.focus()}})
async function work(fn:()=>Promise<void>){if(busy.value)return;busy.value=true;emit('busy',true);error.value='';try{await fn()}catch(e){error.value=readableError(e)}finally{busy.value=false;emit('busy',false)}}
async function refresh(){await work(async()=>{if(props.api.mode!=='online'||!props.api.admin)throw new Error('온라인 운영 관리 연결을 확인해 주세요.');data.value=await props.api.admin()})}
function prepare(input:AdminAction){try{if(!data.value||busy.value)return;validateAdminAction(input,data.value);error.value='';notice.value='';pending.value=input}catch(e){error.value=readableError(e)}}
function prepareRole(){if(!role.value){error.value='교사 또는 학생 계정을 선택해 주세요.';return}prepare({action:'role',user_id:roleUserId.value,role:role.value,approved:roleApproved.value})}
function prepareStudent(){const existing=data.value?.students.find(item=>item.user_id===studentUserId.value);prepare({action:'student',user_id:studentUserId.value,...(existing?{student_id:existing.id}:{}),student_number:studentNumber.value.trim(),academic_year:year.value,school_stage:stage.value,grade:grade.value,name:studentName.value.trim()})}
function prepareAssignment(){prepare({action:'assign',student_id:assignedStudentId.value,teacher_user_id:assignedTeacherId.value,active:assignmentActive.value})}
async function save(){await work(async()=>{if(!pending.value||!data.value||!props.api.administer||!props.api.admin)throw new Error('등록할 내용을 다시 선택해 주세요.');validateAdminAction(pending.value,data.value);await props.api.administer(pending.value);pending.value=null;notice.value='운영 정보를 저장했습니다.';try{data.value=await props.api.admin()}catch{error.value='저장은 완료했습니다. 목록을 다시 불러와 현재 상태를 확인해 주세요.'}})}
const preview=computed(()=>{const value=pending.value;if(!value)return [];if(value.action==='role')return [['대상 계정',userName(value.user_id)],['상담 역할',value.role==='teacher'?'교사':'학생'],['변경 상태',value.approved?'상담 참여 허용':'상담 참여 해제']];if(value.action==='student')return [['학생 계정',userName(value.user_id)],['학생 이름',value.name],['학년도·학번',`${value.academic_year}학년도 · ${value.student_number}`],['학교급·학년',`${value.school_stage==='high'?'고등학교':'중학교'} ${value.grade}학년`],['학생 연결',value.student_id?'기존 학생의 학번 이력 갱신':'고정 학생 ID 새로 연결']];return [['학생',studentLabel(value.student_id)],['담당 교사',userName(value.teacher_user_id)],['변경 상태',value.active?'현재 담당 교사로 배정':'담당 배정 해제']]})
onMounted(()=>{void refresh()})
onBeforeUnmount(()=>emit('busy',false))
</script>

<template>
<main id="main" class="admin-page">
 <header class="admin-heading"><div><span class="eyebrow">상담 운영 관리</span><h1>학생과 상담 교사를 연결합니다.</h1><p>학교 계정을 확인하고 상담 참여 권한, 학번, 담당 관계를 차례로 등록합니다.</p></div><div class="button-row"><button v-if="canReturn" class="secondary" :disabled="busy" @click="emit('close')"><ArrowLeft :size="16"/>상담으로 돌아가기</button><button class="secondary" :disabled="busy" @click="refresh"><RefreshCw :size="16"/>목록 다시 불러오기</button></div></header>
 <p v-if="error&&!pending" class="inline-note warning" role="alert"><AlertCircle :size="18"/>{{error}}</p><p v-if="notice" class="inline-note success" role="status"><Check :size="18"/>{{notice}}</p><p v-if="busy" class="admin-progress" role="status"><LoaderCircle class="spin" :size="18"/>운영 정보를 확인하고 있습니다.</p>
 <template v-if="data">
 <div class="admin-stats"><div><ShieldCheck :size="21"/><span>승인 상담 교사<strong>{{approvedTeachers}}명</strong></span></div><div><Users :size="21"/><span>등록 학생<strong>{{activeStudents}}명</strong></span></div><div><UserRoundPlus :size="21"/><span>현재 담당 관계<strong>{{activeAssignments}}건</strong></span></div></div>
 <div class="admin-forms">
  <section class="card"><div class="section-heading"><span class="step">01</span><div><h2>상담 참여 권한</h2><p>학교의 교사·학생 구분을 그대로 사용합니다.</p></div></div><form novalidate @submit.prevent="prepareRole"><fieldset :disabled="busy"><label>권한을 확인할 학교 계정<select v-model="roleUserId" required><option value="" disabled>기존 계정 선택</option><option v-for="user in data.users" :key="user.id" :value="user.id">{{userLabel(user)}}</option></select></label><div v-if="roleUser" class="admin-target"><strong>{{roleUser.name}}</strong><p>학교 구분: {{roleUser.role}} · {{roleUser.approved?'학교 승인 완료':'학교 승인 대기'}}</p><p>연결할 상담 역할: {{role==='teacher'?'교사':role==='student'?'학생':'해당 없음'}}</p><details><summary>계정 식별 정보</summary><code>{{roleUser.id}}</code></details></div><label class="check-label"><input v-model="roleApproved" type="checkbox" :disabled="!role||(!roleUser?.approved&&!roleApproved)">상담 참여 허용</label><p v-if="roleUser&&!roleUser.approved" class="help">학교 회원 승인을 먼저 완료해야 상담 참여를 허용할 수 있습니다.</p><button class="primary wide" :disabled="!role">권한 변경 확인</button></fieldset></form></section>
  <section class="card"><div class="section-heading"><span class="step">02</span><div><h2>학생과 학번 연결</h2><p>기존 학생 계정에 학년도별 학번을 연결합니다.</p></div></div><form novalidate @submit.prevent="prepareStudent"><fieldset :disabled="busy"><label>학생 학교 계정<select v-model="studentUserId" required><option value="" disabled>학생 계정 선택</option><option v-for="user in studentUsers" :key="user.id" :value="user.id" :disabled="!user.approved">{{userLabel(user)}}</option></select></label><div class="field-grid"><label>학생 이름<input v-model="studentName" required maxlength="80" autocomplete="off"></label><label>학번<input v-model="studentNumber" required inputmode="numeric" pattern="[0-9]{4,8}" maxlength="8" placeholder="예: 10101"></label></div><div class="field-grid three"><label>학년도<input v-model.number="year" required type="number" min="2020" max="2100"></label><label>학교급<select v-model="stage"><option value="high">고등학교</option><option value="middle">중학교</option></select></label><label>학년<select v-model.number="grade"><option :value="1">1학년</option><option :value="2">2학년</option><option :value="3">3학년</option></select></label></div><p class="help">이미 연결된 학생은 같은 고정 학생 ID를 사용합니다. 학년이 바뀌면 새 학년도의 학번을 등록합니다.</p><button class="primary wide">학생 등록 확인</button></fieldset></form></section>
  <section class="card"><div class="section-heading"><span class="step">03</span><div><h2>담당 교사 배정</h2><p>등록 학생과 승인된 상담 교사를 연결합니다.</p></div></div><form novalidate @submit.prevent="prepareAssignment"><fieldset :disabled="busy"><label>배정할 등록 학생<select v-model="assignedStudentId" required><option value="" disabled>등록 학생 선택</option><option v-for="student in data.students" :key="student.id" :value="student.id">{{studentLabel(student.id)}}{{student.active?'':' · 비활성'}}</option></select></label><label>담당 교사 계정<select v-model="assignedTeacherId" required><option value="" disabled>교사 계정 선택</option><option v-for="user in teachers" :key="user.id" :value="user.id">{{userLabel(user)}}{{data.roles.some(item=>item.user_id===user.id&&item.role==='teacher'&&item.approved)?' · 상담 승인':' · 상담 권한 확인 필요'}}</option></select></label><label class="check-label"><input v-model="assignmentActive" type="checkbox">현재 담당 교사로 배정</label><p class="help">체크를 해제하면 이 학생에 대한 담당 관계를 철회합니다. 상담 기록은 보존합니다.</p><button class="primary wide">배정 변경 확인</button></fieldset></form></section>
 </div>
 <section class="card admin-roster"><div class="admin-roster-heading"><div><h2>등록된 담당 관계</h2><p class="help">배정 화면에서 학생과 교사를 선택하면 현재 상태를 불러옵니다.</p></div><label>학생·교사 검색<input v-model="search" placeholder="이름 또는 학번"></label></div><div class="admin-table-wrap"><table><thead><tr><th>학생</th><th>상담 교사</th><th>담당 상태</th></tr></thead><tbody><tr v-for="item in assignmentRows" :key="item.student_id+item.teacher_user_id"><td>{{studentLabel(item.student_id)}}</td><td>{{userName(item.teacher_user_id)}}</td><td><span class="badge" :class="{success:item.active}">{{item.active?'현재 담당':'배정 해제'}}</span></td></tr></tbody></table><p v-if="!assignmentRows.length" class="admin-empty">{{search?'검색한 담당 관계가 없습니다.':'등록된 담당 관계가 없습니다.'}}</p></div></section>
 </template>
 <dialog ref="dialog" class="admin-dialog" aria-labelledby="admin-confirm-title" @cancel.prevent="!busy&&(pending=null)"><template v-if="pending"><header><h2 id="admin-confirm-title">등록할 내용을 확인해 주세요.</h2><button class="icon-button" :disabled="busy" aria-label="확인 창 닫기" @click="pending=null"><X :size="19"/></button></header><dl><div v-for="row in preview" :key="row[0]"><dt>{{row[0]}}</dt><dd>{{row[1]}}</dd></div></dl><p v-if="error" class="inline-note warning" role="alert">{{error}}</p><p class="help">확인한 대상과 상태를 서버에 저장합니다. 학교 계정과 담당 학생이 맞는지 확인해 주세요.</p><div class="modal-actions"><button class="secondary" :disabled="busy" @click="pending=null">돌아가기</button><button class="primary" :disabled="busy" @click="save"><Check :size="17"/>확인하고 저장</button></div></template></dialog>
</main>
</template>
