<script setup lang="ts">
import {computed,ref} from 'vue'
import {BookOpen,ArrowRight} from 'lucide-vue-next'
import {schoolMatches,type SchoolContext,type SchoolAssessment} from '../lib/schoolContext'
import type {Student} from '../lib/types'
const props=defineProps<{data:SchoolContext;student:Student;subjects:string[];locked:boolean}>()
const emit=defineEmits<{adopt:[task:SchoolAssessment]}>()
const query=ref(''),semester=ref<number|null>(null),limit=ref(3)
const matches=computed(()=>schoolMatches(props.data,props.student,props.subjects,query.value,semester.value))
function showAll(){limit.value=props.data.assessments.length}
</script>
<template>
 <section class="card school-context"><div class="profile-section-title"><div><h2>학교 과제·활동 자료 연결</h2><p>입력한 학년도·학년·실제 이수 과목으로 계획 자료를 찾습니다. 현행 과제 여부는 담당 교사에게 확인합니다.</p></div><BookOpen :size="21"/></div>
  <div class="school-filters"><label>계획 자료 학기<select v-model="semester"><option :value="null">전체 학기</option><option :value="1">1학기</option><option :value="2">2학기</option></select></label><label>탐색 참고 검색<input v-model="query" maxlength="100" placeholder="관심 키워드로 다른 과제·활동도 탐색"></label></div>
  <p v-if="!subjects.length" class="profile-empty">먼저 학생 기본자료에 실제 이수 과목을 입력하세요. 탐색 검색은 현재 수강이나 전공 적합성을 판정하지 않습니다.</p>
  <p v-if="student.school_stage==='middle'" class="inline-note">중학생에게 고등학교 자료는 진학 후 학습을 살펴보는 탐색 참고입니다. 현재 해야 할 과제로 적용하지 않습니다.</p>
  <template v-for="group in [{label:'학년도·학년·이수 과목이 맞는 계획 자료',items:matches.selected,reference:false},{label:'다른 학년·학년도 또는 관심 키워드 탐색 참고',items:matches.reference,reference:true}]" :key="group.label"><div v-if="group.items.length" class="school-task-group"><h3>{{group.label}} <span class="badge">{{group.items.length}}개</span></h3><article v-for="task in group.items.slice(0,limit)" :key="task.id" class="school-task"><div class="school-task-meta"><span>{{task.academic_year}}학년도 · {{task.grade}}학년 · {{task.semester}}학기 · {{task.subject}}</span><span class="badge">{{group.reference?'탐색 참고':'현행 여부 확인 필요'}}</span></div><h4>{{task.title}}</h4><p v-if="task.learning_topics.length">주제: {{task.learning_topics.join(' · ')}}</p><p>원문 시기: {{task.timing||'명시된 시기 없음'}}</p><details><summary>절차·산출물·허용 조건과 출처 확인</summary><div><h5>절차</h5><ol v-if="task.steps.length"><li v-for="(step,i) in task.steps" :key="i">{{step}}</li></ol><p v-else>원문에서 추가 확인합니다.</p><h5>산출물</h5><ul><li v-for="(output,i) in task.outputs" :key="i">{{output}}</li></ul><p v-if="!task.outputs.length">산출물을 별도로 정리하지 않았습니다. 절차·과제명을 확인하세요.</p><h5>조건과 AI 관련 원문</h5><ul><li v-for="(condition,i) in task.conditions" :key="i">{{condition}}</li></ul><p>{{task.ai_status||'AI 허용 여부는 별도로 확인합니다.'}}</p><template v-if="task.rubric_excerpts?.length"><h5>채점표 발췌 · 별도 필수조건으로 단정하지 않음</h5><ul><li v-for="(excerpt,i) in task.rubric_excerpts" :key="i">{{excerpt}}</li></ul></template><template v-if="task.issues?.length"><h5>원문에서 추가 확인할 사항</h5><ul><li v-for="(issue,i) in task.issues" :key="i">{{issue}}</li></ul></template><p v-if="task.summary_note">{{task.summary_note}}</p><small>출처: {{task.source_label}} · 개정 {{task.revision}}<br>자료 ID: {{task.source_ref.source_id}}<br>원문 위치: <code>{{task.source_ref.json_pointer}}</code></small></div></details><button class="text-button" :disabled="locked" @click="emit('adopt',task)">이 자료를 전략에 참고 <ArrowRight :size="15"/></button></article><button v-if="group.items.length>limit" class="text-button" @click="showAll">계획 자료 더 보기</button></div></template>
  <p v-if="subjects.length&&!matches.selected.length" class="help">입력한 학년도·학년·과목에 맞는 계획 자료가 없습니다. 과목명을 확인하거나 다른 자료를 탐색 참고로 살펴보세요.</p>
  <details class="school-activities"><summary>학교 활동 자료 둘러보기 · {{matches.activities.length}}개</summary><article v-for="item in matches.activities.slice(0,limit)" :key="item.id"><h4>{{item.name||item.title}}</h4><p>{{item.description}}</p><p class="activity-grade">{{item.grade_range?.length?'대상: '+(item.school_stage==='high'?'고등학교 ':item.school_stage==='middle'?'중학교 ':'')+item.grade_range.join('·')+'학년':'대상 학년 확인 필요'}}</p><span v-if="item.grade_range?.length&&!item.grade_range.includes(student.grade)" class="badge">입력 학년과 대상이 다름 · 탐색 참고</span><small>개설·참여 가능 여부 확인 필요 · {{item.school_year||'연도 원문 확인'}}{{item.semester?' · '+item.semester+'학기':''}}<br>출처: {{item.source_label}} · 개정 {{item.revision}} · {{item.source_ref.source_id}}<br><code>{{item.source_ref.json_pointer}}</code></small></article><button v-if="matches.activities.length>limit" class="text-button" @click="showAll">활동 자료 더 보기</button></details>
  <p class="help">자료를 참고하면 빈 교과·탐구 계획과 교사 근거 메모에 출처를 추가합니다. 기존 계획을 덮어쓰거나 자동 저장하지 않습니다.</p><small class="school-review-date">자료 검토 기준: {{data.reviewed_on}}. 자료에 없는 마감일이나 참여 조건을 생성하지 않습니다.</small>
 </section>
</template>
